yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500

handler404 = "posts.views.page_not_found"  # noqa
handler500 = "posts.views.server_error"  # noqa

urlpatterns = [
    path('admin/myadmin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

yatube/templates/include/base.html
<!doctype html>
<html>

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}The Last Social Media You'll Ever Need{% endblock %} | Yatube</title>
    <!-- Загрузка статики -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
  </head>

  <body>
    {% include 'include/nav.html' %}
    <main>
      <div class="container">
        <h1>{% block header %}The Last Social Media You'll Ever Need{% endblock %}</h1>
        {% block content %}
          <!-- Содержимое страницы -->
        {% endblock %}
      </div>
    </main>
    {% include 'include/footer.html' %}
  </body>

</html>

yatube/templates/include/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
  <p class="m-0 text-dark text-center ">
    <a href="{% url 'about:author' %}">Об авторе</a>
    <a href="{% url 'about:tech' %}">О технологиях</a>
  </p>
  <p class="m-0 text-dark text-center ">Социальная сеть <span style="color:red">Ya</span>tube
    © 2021, все права защищены. </p>
</footer>

yatube/templates/include/header.html
<div id="top-of-site">
  {# здесь описана шапка сайта, она повторяется на всех страницах проекта #}
  <img src="images/logo.jpg" alt="Yatube">
  <div id="site-name">Yatube</div>
</div>

yatube/templates/include/menu.html
{% if user.is_authenticated %}
<div class='row'>
  <ul class='nav nav-tabs'>
    <li class='nav-item'>
      <a class='nav-link {% if index %}active{% endif %}' href='{% url "index" %}'>
          Все авторы
      </a>
    </li>
    <li class='nav-item'>
      <a class='nav-link {% if follow %}active{% endif %}' href='{% url "follow_index" %}'>
        Избранные авторы
      </a>
    </li>
  </ul>
</div>
{% endif %} 

yatube/templates/include/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href='{% url "index" %}'><span style="color:red">Ya</span>tube</a>
  <nav class="my-2 my-md-0 mr-md-3">
    {% if user.is_authenticated %}
      Пользователь: {{ user.username }}.
      <a class='p-2 text-dark' href='{% url "new_post" %}'><button type='button' class='btn btn-primary btn-sm'>Новая запись</button></a>
      <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
      <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
    {% else %}
      <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
      <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
    {% endif %}
  </nav>
</nav>

yatube/templates/include/paginator.html
{% if page.has_other_pages %}
  <nav>
    <ul class="pagination">
      {% if page.has_previous %}
        <li class="page-item">
          <a
            class="page-link"
            href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">&laquo; Предыдущая</span>
        </li>
      {% endif %}
      {% for i in page.paginator.page_range %}
        {% if page.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}
              <span class="sr-only">(текущая)</span>
            </span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page.has_next %}
        <li class="page-item">
          <a
            class="page-link"
            href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Следующая &raquo;</span>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}